# Generated by Django 5.1.6 on 2025-03-12 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchallenge',
            name='completion_date',
            field=models.DateField(blank=True, help_text="Challenge'ın tamamlandığı tarih", null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='current_stage',
            field=models.IntegerField(default=1, help_text="Çok aşamalı challenge'larda mevcut aşama"),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='failure_reason',
            field=models.CharField(blank=True, help_text='Challenge başarısız olma sebebi', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='stage1_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userchallenge',
            name='stage2_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
