# Generated by Django 5.1.6 on 2025-03-12 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_trade_trade_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='profit_loss_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Kar/Zarar Yüzdesi (%)'),
        ),
    ]
