# Generated by Django 5.1.6 on 2025-03-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_trade_custom_result_alter_trade_trade_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='stop_loss',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='take_profit',
        ),
        migrations.AddField(
            model_name='trade',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trade',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_date',
            field=models.DateTimeField(verbose_name='Giriş Tarihi'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='entry_price',
            field=models.DecimalField(decimal_places=6, max_digits=15, verbose_name='Giriş Fiyatı'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Çıkış Tarihi'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='exit_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True, verbose_name='Çıkış Fiyatı'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lot Büyüklüğü'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notlar'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='profit_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Kar/Zarar ($)'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='symbol',
            field=models.CharField(max_length=20, verbose_name='Sembol'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(choices=[('BUY', 'Alış'), ('SELL', 'Satış')], max_length=10, verbose_name='İşlem Tipi'),
        ),
    ]
